jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: '*'
    - run: npm install
    - run: npm run build
    - run: |
        npm pack --pack-destination=.github
        for file in .github/*.tgz; do mv "$file" "${file%-*}.tgz"; done
    - if: ${{github.ref == 'refs/tags/latest'}}
      uses: softprops/action-gh-release@v1
      with:
        append_body: true
        fail_on_unmatched_files: true
        files: |
          .github/*.tgz
        prerelease: true
  build-pnpm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: pnpm/action-setup@v2
      with:
        version: '*'
    - uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: '*'
    - run: pnpm install
    - run: pnpm build
on:
  push:
    tags:
    - latest
  workflow_dispatch:
permissions: {}
